---
abstract: 'A framework for parsing PseudoPod'
author:
  - 'Allison Randal (allison@perl.org)'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-PseudoPod
provides:
  Pod::PseudoPod:
    file: lib/Pod/PseudoPod.pm
    version: 0.17
  Pod::PseudoPod::Checker:
    file: lib/Pod/PseudoPod/Checker.pm
    version: 0.17
  Pod::PseudoPod::DocBook:
    file: lib/Pod/PseudoPod/DocBook.pm
    version: 0.17
  Pod::PseudoPod::HTML:
    file: lib/Pod/PseudoPod/HTML.pm
    version: 0.17
  Pod::PseudoPod::Index:
    file: lib/Pod/PseudoPod/Index.pm
    version: 0.17
  Pod::PseudoPod::Text:
    file: lib/Pod/PseudoPod/Text.pm
    version: 0.17
requires:
  HTML::Entities: 0
  Pod::Simple: 3.02
  Text::Wrap: 98.112902
resources:
  license: http://dev.perl.org/licenses/
version: 0.17
